name: ghc-wasm-darwin-bindist
runs:
  using: composite
  steps:

    - name: setup-haskell
      uses: haskell-actions/setup@v2

    - name: build-hadrian
      working-directory: ${{ runner.temp }}
      shell: bash
      run: |
        git clone --branch=${{ matrix.branch }} --depth=1 --recurse-submodules --shallow-submodules --jobs 32 ${{ matrix.remote }}
        cd ghc
        ./hadrian/build --version

    - name: setup-cabal-deps
      shell: bash
      run: |
        cabal install \
          --overwrite-policy=always \
          alex-3.5.1.0 \
          happy-1.20.1.1

    - name: setup-ghc-wasm-meta
      shell: bash
      run: |
        curl https://gitlab.haskell.org/haskell-wasm/ghc-wasm-meta/-/raw/master/bootstrap.sh | PREFIX=${{ runner.temp }}/.ghc-wasm SKIP_GHC=1 sh
        ${{ runner.temp }}/.ghc-wasm/add_to_github_path.sh

    - name: configure-ghc
      working-directory: ${{ runner.temp }}/ghc
      shell: bash
      run: |
        ./boot
        ./configure $CONFIGURE_ARGS

    - name: build-ghc
      working-directory: ${{ runner.temp }}/ghc
      shell: bash
      run: |
        hadrian/build --no-color --no-progress --no-time --flavour=${{ matrix.flavour }} --docs=none -j binary-dist-dir test:all_deps _build/stage0/bin/wasm32-wasi-{haddock,hpc,runghc}

    - name: build-bindist
      working-directory: ${{ runner.temp }}/ghc
      shell: bash
      run: |
        BINDIST_NAME=$(basename _build/bindist/*)
        tar --use-compress-program="zstd --ultra -22 --threads=0" -cf _build/bindist/$BINDIST_NAME.tar.zst -C _build/bindist $BINDIST_NAME

    - name: upload-bindist
      uses: actions/upload-artifact@v4
      with:
        name: ghc-wasm-${{ matrix.arch }}-darwin-${{ matrix.branch }}-bindist
        path: ${{ runner.temp }}/ghc/_build/bindist/*.tar.zst

    - name: test-ghc
      working-directory: ${{ runner.temp }}/ghc
      shell: bash
      run: |
        hadrian/build --no-color --no-progress --no-time --flavour=${{ matrix.flavour }} --docs=none -j test
