name: ghc-wasm-aarch64-linux-bindist

on:
  pull_request:
    paths:
      - .github/workflows/aarch64-linux-bindist.yml
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'

jobs:
  ghc-wasm-aarch64-linux-bindist:
    name: ghc-wasm-aarch64-linux-bindist
    runs-on:
      - self-hosted
      - Linux
      - ARM64
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build & test
        run: |
          podman run \
            --rm \
            --init \
            --network host \
            --pull always \
            --volume $PWD:/workspace \
            --workdir /workspace \
            alpine \
            /workspace/alpine-build.sh

      - name: upload-bindist
        uses: actions/upload-artifact@v4
        with:
          name: ghc-wasm-aarch64-linux-bindist
          path: ghc-*.tar.zst
