name: ghc-wasm-darwin-bindist

on:
  pull_request:
    paths:
      - .github/actions/darwin-bindist/action.yml
      - .github/workflows/darwin-bindist.yml
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'

jobs:
  ghc-wasm-aarch64-darwin-bindist:
    name: ghc-wasm-aarch64-darwin-${{ matrix.branch }}-bindist
    runs-on:
      - ARM64
      - macOS
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            branch: master
            remote: https://gitlab.haskell.org/ghc/ghc.git
            flavour: release+text_simdutf
          - arch: aarch64
            branch: ghc-9.12
            remote: https://gitlab.haskell.org/TerrorJack/ghc.git
            flavour: release+text_simdutf
          - arch: aarch64
            branch: ghc-9.10
            remote: https://gitlab.haskell.org/TerrorJack/ghc.git
            flavour: release
    env:
      MACOSX_DEPLOYMENT_TARGET: "13.0"
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: ghc-wasm-darwin-bindist
        uses: ./.github/actions/darwin-bindist

  ghc-wasm-x86_64-darwin-bindist:
    needs: ghc-wasm-aarch64-darwin-bindist
    name: ghc-wasm-x86_64-darwin-${{ matrix.branch }}-bindist
    runs-on:
      - X64
      - macOS
    strategy:
      matrix:
        include:
          - arch: x86_64
            branch: master
            remote: https://gitlab.haskell.org/ghc/ghc.git
            flavour: release+text_simdutf
    env:
      MACOSX_DEPLOYMENT_TARGET: "13.0"
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: ghc-wasm-darwin-bindist
        uses: ./.github/actions/darwin-bindist
